# Generated by Django 2.0.5 on 2018-05-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firefighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('CFO', 'Chief Fire Officer'), ('DCFO', 'Deputy Chief Fire Officer'), ('SSO', 'Senior Station Officer'), ('SO', 'Station Officer'), ('SFF', 'Senior Firefighter'), ('QFF', 'Qualified Firefighter'), ('FF', 'Firefighter'), ('RFF', 'Recruit Firefighter'), ('OS', 'Operational Support')], default='RFF', max_length=50, verbose_name='Rank')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('Start Date', models.DateField()),
                ('status', models.CharField(choices=[('AV', 'Available'), ('OD', 'On Duty'), ('UN', 'Unavailable'), ('LV', 'Leave')], default='Available', max_length=20, verbose_name='Status')),
                ('driver', models.BooleanField(default=False, verbose_name='Driver')),
                ('officer', models.BooleanField(default=False, verbose_name='Officer Qualified')),
            ],
            options={
                'verbose_name': 'Firefighter',
                'verbose_name_plural': 'Firefighters',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='firefighter',
            name='teams',
            field=models.ManyToManyField(to='fire.Team'),
        ),
    ]
