# Generated by Django 2.0.5 on 2018-05-28 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firefighter',
            name='Start Date',
        ),
        migrations.AddField(
            model_name='firefighter',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
