# Generated by Django 2.0.5 on 2018-05-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_auto_20180528_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='firefighter',
            name='order',
            field=models.IntegerField(default=2, verbose_name='Order'),
            preserve_default=False,
        ),
    ]
